/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 18 14:08:19 GMT 2022
 */

package org.eclipse.cargotracker.domain.model.cargo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.eclipse.cargotracker.domain.model.cargo.Cargo;
import org.eclipse.cargotracker.domain.model.location.Location;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Cargo_ESTest extends Cargo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Cargo cargo0 = new Cargo();
      Cargo cargo1 = new Cargo();
      // Undeclared exception!
      try { 
        cargo0.equals(cargo1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.cargotracker.domain.model.cargo.Cargo", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Cargo cargo0 = new Cargo();
      boolean boolean0 = cargo0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Cargo cargo0 = new Cargo();
      boolean boolean0 = cargo0.equals(cargo0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Cargo cargo0 = new Cargo();
      boolean boolean0 = cargo0.equals("M>M[s??@>S");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Cargo cargo0 = new Cargo();
      Location location0 = cargo0.getOrigin();
      assertNull(location0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Cargo cargo0 = new Cargo();
      // Undeclared exception!
      try { 
        cargo0.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.cargotracker.domain.model.cargo.Cargo", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Cargo cargo0 = new Cargo();
      // Undeclared exception!
      try { 
        cargo0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.eclipse.cargotracker.domain.model.cargo.Cargo", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Cargo cargo0 = new Cargo();
      cargo0.setOrigin((Location) null);
  }
}
